### ISSUE TITLE
Problem Ubuntu 22.04 sdrplay API 3.07

### ISSUE THREAD

**Issue by khseal** [marcogrecopriolo/guglielmo#16]
Does not work, but sees the service.
~/guglielmo/build$ ./guglielmo -v
PLAYV3: functions loaded
PLAYV3: api opened
PLAYV3: api version 3,070000 detected
PLAYV3: 1 devices detected
PLAYV3: sdrplay_api_Init failed sdrplay_api_Fail
PLAYV3: stopping

**Comment by marcogrecopriolo** [comment]
I don't want to sound unhelpful but I only have had an RSP1A on load from SDRplay for a short period of time and I haven't used it since.
Is this happening with your own build or the appImage?
If this is happening with the appImage, can you do a build, and I might try to debug remotely?
If this is happening with your build, what say the appImage?

**Comment by khseal** [comment]
I compiled from source.I have a RSP1. It doesn't seem to be supported by the latest version of sdrplay in the application.
The old version of SDRplay is now working.
If you are interested in adding support RSP1, I can give remote access.
