### ISSUE TITLE
Windows Noob

### ISSUE THREAD

**Issue by TimmyNow** [marcogrecopriolo/guglielmo#18]
I am having some issues installing on windows, with the instructions provided. I appear to be missing some files, can anyone point me in the right direction? I really want to get dab set up on the RTL-SDR v4.

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.39.33520.0
-- The CXX compiler identification is MSVC 19.39.33520.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at CMakeLists.txt:137 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake
    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

**Comment by marcogrecopriolo** [comment]
Sorry, I'm on hols and away from my build machine until early next week. I'll refresh my memory as soon  as I'm back.

**Comment by marcogrecopriolo** [comment]
I have tried my build environment, and I can clone and directly build with MSVC with both nmake and qmake, although the process is painful (nmake stops half way with errors, but if I restart it just continues).
On windows, I find qmake slightly less painful than cmake, and I suggest that you use qmake instead.

Putting together the build environment was, no surprise, painful - in particular you have to make sure that your PATH points to the correct Qt environment for your compiler, eg for MSVC, your path needs to contain

c:\Qt\Qt5.12.12\5.12.12\msvc2017\bin

or qmake / cmake will fail to find the Qt environment.
This should get you past your current issue.
Next, you have to build your qwt from source using your actual qt / compiler environment.
You cannot just mix and match MSVC and mingw.

Next, the whole build process is fickle with regards to where it picks up the libraries.
For Msys64, I found that the best place to put the needed libraries is /usr/local/lib - you need libfaad, libfftw3f, libsndfile, portaudio, samplerate, and of course the qwt that you built earlier
For MSCV, what works for me is to have a 'libraries' directory at the same level as the source you cloned (that is, qmake will point LIBPATH to ..\libraries.
On top of the previous ones, you'll probably need libusb, libwinpthreads and msvcr100.
Once you have done, in order to build the installer, you will have to put in windows-bin all the needed libraries plus the drivers.

**Comment by marcogrecopriolo** [comment]
FYI - you don't need to rebuild the product to use RTLSDR V4.
Just use the existing guglielmo V0.5 installer, and then replace rtlsdr.dll with the one provided by https://github.com/rtlsdrblog/rtl-sdr-blog/releases/download/V1.3.4/Release.zip
Be use to use the x86 (32 bit) library.
Everything should work without issue.

When I have a second I will build installers with the new RTLSDR driver.

HTH

**Comment by marcogrecopriolo** [comment]
I have added an installer with the RTLSDR V4 library - could you try it out?

https://github.com/marcogrecopriolo/guglielmo/releases/download/v0.5/guglielmo-installer-with-V4-0.5.exe
