### ISSUE TITLE
Is there autoplay key?

### ISSUE THREAD

**Issue by EscapedM** [marcogrecopriolo/guglielmo#19]
Software looks pretty cool compared to SDRShark. 
Requesting cli to control app & keys to choose config/preset/autoplay.

**Comment by marcogrecopriolo** [comment]
I have added some keyboard shortcuts (will add a quick help, next).
Re the CLI, that requires a non trivial amount of infrastructure, so that is unlikely to come, but!
We have MPRIS control, so have you tried playerctl?
The following works quite happily:

playerctl -p guglielmo play
playerctl -p guglielmo volume 0.1
playerctl -p guglielmo stop
...etc
